# Default configuration for the computeblade-agent

log:
  mode: production  # production, development

# Listen configuration
listen:
  metrics: ":9666"
  grpc: /tmp/computeblade-agent.sock

# Hardware abstraction layer configuration
hal:
  # For the default fan unit, fanspeed measurement is causing a tiny bit of CPU laod.
  # Sometimes it might not be desired
  rpm_reporting_standard_fan_unit: true

# Idle LED color, values range from 0-255
idle_led_color:
  red: 0
  green: 16
  blue: 0

# Identify LED color
identify_led_color:
  red: 16
  green: 0
  blue: 16

# Critical LED color
criticalLedColor:
  red: 64
  green: 0
  blue: 0

# Enable/disable stealth mode; turns off all LEDs on the blade
stealth_mode: false


# Simple fan-speed controls based on the SoC temperature
fan_controller:
  # For now, this is only supporting a two-step configuration.
  steps:
    - temperature: 45
      percent: 40
    - temperature: 55
      percent: 80
# Critical temperature threshold
critical_temperature_threshold: 60
